### ISSUE TITLE
Item dinamic data 

### ISSUE THREAD

**Issue by luiscolmenares** [jpchateau/Interactive-Image#4] opened 2019-10-13 18:21 UTC
@jpchateau , thanks for sharing this library,

I want to use it in order to show some data coming from connected devices. This data comes from an Angular Object and gets updated often (imagine a floor-plan where a hotspot is a sensor with temperature data, and for every click, a new temperature read would come).

I was able to get it working with static mock data, but I am not getting the data when trying ti use ng-bind data.

Any suggestion?

Source code:

```

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<script type="text/javascript">
    var app = angular.module('myApp', []);
    app.controller('myCtrl', function($scope) {
      $scope.temperature = "45";
    });
</script>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Image - Examples</title>

    <!-- Specific styles of a scene -->
    <style>
        .interactive-image {
            margin: auto;
            width: 800px;
            height: 600px;
            background-image: url('https://www.roomsketcher.com/wp-content/uploads/2015/12/RoomSketcher-3D-Floor-Plan_800x600.jpg');
        }
    </style>

    <!-- Include Interactive Image jQuery plugin Styles -->
<link href="https://cdn.jsdelivr.net/npm/interactiveimagejs@2.5.0/dist/interactive-image.css" rel="stylesheet" type="text/css" />
<body>
    <!-- Main container of a scene -->
<!-- msg payload test -->
<div ng-bind-html="temperature"></div>

<!-- msg payload test -->
<div ng-app="myApp" ng-controller="myCtrl">
    <p ng-bind="temperature"></p>

    <div id="my-interactive-image"></div>
    
</div>    
    <!-- Include jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script>
        // Plugin Items collection
        var items = [
            // Text items
           
            {
                type: "text",
                title: "T Sensor",
                description: 'temperature: <p ng-bind="temperature"></p>',
                position: {
                    left: 300,
                    top: 50
                },
                link: {
                    url: "#",
                    label: "View more >"
                }
            }
        ];

        // Plugin configuration
        var options = {
            debug: true,     // console logs
            allowHtml: true, // allow HTML markup
            shareBox: false,  // display the social media share box
            socialMedia: {   // configuration of the social media share box
                url: "https://www.jpchateau.com/demo/interactive-image",
                text: "Clouded Leopard",
                hashtags: ["jQuery", "cloudedLeopard"],
                twitterUsername: "jpchateau",
            }
        };

        // Plugin activation
        $(document).ready(function() {
            $("#my-interactive-image").interactiveImage(items, options);
        });
    </script>

    <!-- Include Interactive Image jQuery plugin JavaScript -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/interactiveimagejs@2.5.0/dist/interactive-image.js"></script>

</body>
</html>
```

**Comment by jpchateau** [comment] 2019-10-13 23:08
Hi @luiscolmenares!
I didn't imagine this library could be used for reading dynamic data, especially for home automation. It is a nice idea!
Unfortunately, I don't know angularjs. But I will try to look at this issue in the next few days (thank you for having shared your code, it should be easy to reproduce the problem).

**Comment by jpchateau** [comment] 2019-10-15 21:54
Hello @luiscolmenares!

I think this issue is related to the use of the plugin with angularjs, as it was not designed to fit this need.
Actually, when the DOM is injected into the main DIV, it is not handled by angularjs, so it is necessary to trigger some compilation tasks.

Good news: I found a workaround. Bad news: it is not clean, and probably is a bad practice.

The angularjs controller looks like:
```javascript
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope, $compile) {
    $scope.temperature = "45";
    $scope.afterRendering = function(html) {
        $compile(html)($scope);      
    };
});
```
Source code of the html page:
```html
<script>
        (...)

	var timer = function() {
		setTimeout(function() {
			var scope = angular.element(document.getElementById("myDiv")).scope();
			scope.$apply(function() {
				scope.afterRendering($('#my-interactive-image'));
			});
		}, 500);
	};

        // Plugin activation
	$(document).ready(function() {
		$("#my-interactive-image").interactiveImage(items, options);
		timer();
	});
</script>
```
After the document is loaded, it lets the plugin the time to build the DOM, then it calls a controller method to compile it.

Tell me if this workaround helped you! I think a proper solution could be to create a directive that executes the plugin and compiles the DOM another time.

**Comment by luiscolmenares** [comment] 2019-10-16 02:04
Hi @jpchateau ,

Thanks for the workaround!. Your comments regarding the DOM load and the controller made me think about the way your library loads the data, and then it clicked!... Why don't we include the item IN the controller? That will make it one-way binding (controller->view)... easier to handle from the library perspective. 

Voila! here is the working code:

```javascript
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular.min.js"></script>
<script type="text/javascript">

	var app = angular.module('myApp', []);
	app.controller('myCtrl', function($scope, $compile) {
		$scope.temperature = "45";
		var items = [        
		{
			type: "text",
			title: "T Sensor",
			description: '<p>Temperature:'+$scope.temperature+'</p>',
			position: {
				left: 300,
				top: 50
			},
			link: {
				url: "#",
				label: "View more >"
			}
		}
		];

// Plugin configuration
var options = {
	debug: true,     // console logs
	allowHtml: true, // allow HTML markup
	shareBox: false,  // display the social media share box
	socialMedia: {   // configuration of the social media share box
		url: "https://www.jpchateau.com/demo/interactive-image",
		text: "Clouded Leopard",
		hashtags: ["jQuery", "cloudedLeopard"],
		twitterUsername: "jpchateau",
	}
};

// Plugin activation
$(document).ready(function() {
	$("#my-interactive-image").interactiveImage(items, options);
});


});
</script>


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Interactive Image - Examples</title>

	<!-- Specific styles of a scene -->
	<style>
		.interactive-image {
			margin: auto;
			width: 800px;
			height: 600px;
			background-image: url('https://www.roomsketcher.com/wp-content/uploads/2015/12/RoomSketcher-3D-Floor-Plan_800x600.jpg');
		}
	</style>

	<!-- Include Interactive Image jQuery plugin Styles -->
	<link href="https://cdn.jsdelivr.net/npm/interactiveimagejs@2.5.0/dist/interactive-image.css" rel="stylesheet" type="text/css" />
	<body>
		<!-- Main container of a scene -->
		<!-- msg payload test -->
		<div ng-bind-html="temperature"></div>
		<!-- end msg payload test -->
		<div ng-app="myApp" ng-controller="myCtrl">
			<p ng-bind="temperature"></p>
			<div id="my-interactive-image"></div>   
		</div>    
		<!-- Include jQuery -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<!-- Include Interactive Image jQuery plugin JavaScript -->
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/interactiveimagejs@2.5.0/dist/interactive-image.js"></script>

	</body>
	</html>
```

This will provide the div with the DOM already build :)

**Comment by jpchateau** [comment] 2019-10-16 22:51
Well done @luiscolmenares, I am glad to see it working!
I close the issue. I think it might be worth it in the future to add a section in the documentation about integrating with JS frameworks.

**Closed by jpchateau** 2019-10-16 22:51 UTC
